# Generated by Django 2.2 on 2019-04-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDict',
            fields=[
                ('chinese_words', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('pinyin', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
    ]
