# Generated by Django 2.2 on 2019-05-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_word', models.CharField(max_length=100)),
                ('pinyin', models.CharField(max_length=250)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user_dict',
                'ordering': ['pinyin', '-count'],
                'abstract': False,
                'unique_together': {('chinese_word', 'pinyin')},
            },
        ),
    ]
