# Generated by Django 2.2 on 2019-04-27 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDict',
            fields=[
                ('chinese_word', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('pinyin', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserDict',
            fields=[
                ('basedict_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transliterator.BaseDict')),
            ],
            bases=('transliterator.basedict',),
        ),
    ]
